.TH "qb Directory Reference" 3 "Sun Dec 2 2018" "Version 1.0.3" "libqb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qb Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBqbarray\&.h\fP"
.br
.RI "This is a dynamic array (it can grow, but without moving memory)\&. "
.ti -1c
.RI "file \fBqbatomic\&.h\fP"
.br
.RI "Basic atomic integer and pointer operations\&. "
.ti -1c
.RI "file \fBqbconfig\&.h\fP"
.br
.ti -1c
.RI "file \fBqbdefs\&.h\fP"
.br
.RI "These are some convience macros and defines\&. "
.ti -1c
.RI "file \fBqbhdb\&.h\fP"
.br
.RI "The handle database is for reference counting objects\&. "
.ti -1c
.RI "file \fBqbipc_common\&.h\fP"
.br
.RI "common types and definitions "
.ti -1c
.RI "file \fBqbipcc\&.h\fP"
.br
.RI "Client IPC API\&. "
.ti -1c
.RI "file \fBqbipcs\&.h\fP"
.br
.RI "Server IPC API\&. "
.ti -1c
.RI "file \fBqblist\&.h\fP"
.br
.RI "This is a kernel style list implementation\&. "
.ti -1c
.RI "file \fBqblog\&.h\fP"
.br
.RI "The logging API provides four main parts (basics, filtering, threading & blackbox)\&. "
.ti -1c
.RI "file \fBqbloop\&.h\fP"
.br
.RI "Main loop manages timers, jobs and polling sockets\&. "
.ti -1c
.RI "file \fBqbmap\&.h\fP"
.br
.RI "This provides a map interface to a Patricia trie, hashtable or skiplist\&. "
.ti -1c
.RI "file \fBqbrb\&.h\fP"
.br
.RI "This implements a ring buffer that works in 'chunks', not bytes\&. "
.ti -1c
.RI "file \fBqbutil\&.h\fP"
.br
.RI "These are some convience functions used throughout libqb\&. "
.in -1c
