.TH "deprecated" 3 "Sun Dec 2 2018" "Version 1.0.3" "libqb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecatedDeprecated List 
 \- 
.IP "\fBGlobal \fBqb_ipcs_connection_stats_get\fP (qb_ipcs_connection_t *c, struct \fBqb_ipcs_connection_stats\fP *stats, int32_t clear_after_read)\fP" 1c
from v0\&.13\&.0 onwards, use qb_ipcs_connection_stats_get_2 
.PP

