.TH "qb_hdb" 3 "Sun Dec 2 2018" "Version 1.0.3" "libqb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qb_hdb
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qbhdb\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBhandle_count\fP"
.br
.ti -1c
.RI "\fBqb_array_t\fP * \fBhandles\fP"
.br
.ti -1c
.RI "uint32_t \fBiterator\fP"
.br
.ti -1c
.RI "void(* \fBdestructor\fP )(void *)"
.br
.ti -1c
.RI "uint32_t \fBfirst_run\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void(* qb_hdb::destructor) (void *)"

.SS "uint32_t qb_hdb::first_run"

.SS "uint32_t qb_hdb::handle_count"

.SS "\fBqb_array_t\fP* qb_hdb::handles"

.SS "uint32_t qb_hdb::iterator"


.SH "Author"
.PP 
Generated automatically by Doxygen for libqb from the source code\&.
