.TH "qb_hdb_overview" 3 "Sun Dec 2 2018" "Version 1.0.3" "libqb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qb_hdb_overviewHandle Database 
 \- The handle database is for reference counting objects\&.
.PP
\fBNote:\fP
.RS 4
Historically, handle database implementation also served internal needs of libqb (e\&.g\&. for IPC services tracking), which was eventually replaced with indirection-less reference counters and their direct modifications\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBqbhdb\&.h\fP 
.RE
.PP

