.TH "qb_hdb_handle" 3 "Sun Dec 2 2018" "Version 1.0.3" "libqb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qb_hdb_handle
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qbhdb\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int32_t \fBstate\fP"
.br
.ti -1c
.RI "void * \fBinstance\fP"
.br
.ti -1c
.RI "int32_t \fBcheck\fP"
.br
.ti -1c
.RI "int32_t \fBref_count\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int32_t qb_hdb_handle::check"

.SS "void* qb_hdb_handle::instance"

.SS "int32_t qb_hdb_handle::ref_count"

.SS "int32_t qb_hdb_handle::state"


.SH "Author"
.PP 
Generated automatically by Doxygen for libqb from the source code\&.
