.TH "qb_ipc_response_header" 3 "Sun Dec 2 2018" "Version 1.0.3" "libqb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qb_ipc_response_header
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qbipc_common\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int32_t id \fB__attribute__\fP ((aligned(8)))"
.br
.ti -1c
.RI "int32_t size \fB__attribute__\fP ((aligned(8)))"
.br
.ti -1c
.RI "int32_t error \fB__attribute__\fP ((aligned(8)))"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int32_t id qb_ipc_response_header::__attribute__ ((aligned(8)))"

.SS "int32_t size qb_ipc_response_header::__attribute__ ((aligned(8)))"

.SS "int32_t error qb_ipc_response_header::__attribute__ ((aligned(8)))"


.SH "Author"
.PP 
Generated automatically by Doxygen for libqb from the source code\&.
