.TH "qb_ipcs_connection_stats" 3 "Sun Dec 2 2018" "Version 1.0.3" "libqb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qb_ipcs_connection_stats
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qbipcs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int32_t \fBclient_pid\fP"
.br
.ti -1c
.RI "uint64_t \fBrequests\fP"
.br
.ti -1c
.RI "uint64_t \fBresponses\fP"
.br
.ti -1c
.RI "uint64_t \fBevents\fP"
.br
.ti -1c
.RI "uint64_t \fBsend_retries\fP"
.br
.ti -1c
.RI "uint64_t \fBrecv_retries\fP"
.br
.ti -1c
.RI "int32_t \fBflow_control_state\fP"
.br
.ti -1c
.RI "uint64_t \fBflow_control_count\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int32_t qb_ipcs_connection_stats::client_pid"

.SS "uint64_t qb_ipcs_connection_stats::events"

.SS "uint64_t qb_ipcs_connection_stats::flow_control_count"

.SS "int32_t qb_ipcs_connection_stats::flow_control_state"

.SS "uint64_t qb_ipcs_connection_stats::recv_retries"

.SS "uint64_t qb_ipcs_connection_stats::requests"

.SS "uint64_t qb_ipcs_connection_stats::responses"

.SS "uint64_t qb_ipcs_connection_stats::send_retries"


.SH "Author"
.PP 
Generated automatically by Doxygen for libqb from the source code\&.
