.TH "qb_ipcs_poll_handlers" 3 "Sun Dec 2 2018" "Version 1.0.3" "libqb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qb_ipcs_poll_handlers
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qbipcs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBqb_ipcs_job_add_fn\fP \fBjob_add\fP"
.br
.ti -1c
.RI "\fBqb_ipcs_dispatch_add_fn\fP \fBdispatch_add\fP"
.br
.ti -1c
.RI "\fBqb_ipcs_dispatch_mod_fn\fP \fBdispatch_mod\fP"
.br
.ti -1c
.RI "\fBqb_ipcs_dispatch_del_fn\fP \fBdispatch_del\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBqb_ipcs_dispatch_add_fn\fP qb_ipcs_poll_handlers::dispatch_add"

.SS "\fBqb_ipcs_dispatch_del_fn\fP qb_ipcs_poll_handlers::dispatch_del"

.SS "\fBqb_ipcs_dispatch_mod_fn\fP qb_ipcs_poll_handlers::dispatch_mod"

.SS "\fBqb_ipcs_job_add_fn\fP qb_ipcs_poll_handlers::job_add"


.SH "Author"
.PP 
Generated automatically by Doxygen for libqb from the source code\&.
