.TH "qb_ipcs_stats" 3 "Sun Dec 2 2018" "Version 1.0.3" "libqb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qb_ipcs_stats
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qbipcs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBactive_connections\fP"
.br
.ti -1c
.RI "uint32_t \fBclosed_connections\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint32_t qb_ipcs_stats::active_connections"

.SS "uint32_t qb_ipcs_stats::closed_connections"


.SH "Author"
.PP 
Generated automatically by Doxygen for libqb from the source code\&.
