.TH "qb_ipcs_service_handlers" 3 "Sun Dec 2 2018" "Version 1.0.3" "libqb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qb_ipcs_service_handlers
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qbipcs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBqb_ipcs_connection_accept_fn\fP \fBconnection_accept\fP"
.br
.ti -1c
.RI "\fBqb_ipcs_connection_created_fn\fP \fBconnection_created\fP"
.br
.ti -1c
.RI "\fBqb_ipcs_msg_process_fn\fP \fBmsg_process\fP"
.br
.ti -1c
.RI "\fBqb_ipcs_connection_closed_fn\fP \fBconnection_closed\fP"
.br
.ti -1c
.RI "\fBqb_ipcs_connection_destroyed_fn\fP \fBconnection_destroyed\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBqb_ipcs_connection_accept_fn\fP qb_ipcs_service_handlers::connection_accept"

.SS "\fBqb_ipcs_connection_closed_fn\fP qb_ipcs_service_handlers::connection_closed"

.SS "\fBqb_ipcs_connection_created_fn\fP qb_ipcs_service_handlers::connection_created"

.SS "\fBqb_ipcs_connection_destroyed_fn\fP qb_ipcs_service_handlers::connection_destroyed"

.SS "\fBqb_ipcs_msg_process_fn\fP qb_ipcs_service_handlers::msg_process"


.SH "Author"
.PP 
Generated automatically by Doxygen for libqb from the source code\&.
