.TH "qb_log_ctl2_arg_t" 3 "Sun Dec 2 2018" "Version 1.0.3" "libqb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qb_log_ctl2_arg_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qblog\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int32_t \fBi32\fP"
.br
.ti -1c
.RI "const char * \fBs\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int32_t qb_log_ctl2_arg_t::i32"

.SS "const char* qb_log_ctl2_arg_t::s"


.SH "Author"
.PP 
Generated automatically by Doxygen for libqb from the source code\&.
