.TH "qb_list_head" 3 "Sun Dec 2 2018" "Version 1.0.3" "libqb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qb_list_head
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qblist\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBqb_list_head\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBqb_list_head\fP * \fBprev\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBqb_list_head\fP* qb_list_head::next"

.PP
Referenced by qb_list_add(), qb_list_add_tail(), qb_list_del(), qb_list_empty(), qb_list_init(), qb_list_is_last(), qb_list_replace(), qb_list_splice(), and qb_list_splice_tail()\&.
.SS "struct \fBqb_list_head\fP* qb_list_head::prev"

.PP
Referenced by qb_list_add(), qb_list_add_tail(), qb_list_del(), qb_list_init(), qb_list_replace(), qb_list_splice(), and qb_list_splice_tail()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libqb from the source code\&.
