.TH "qb_version" 3 "Sun Dec 2 2018" "Version 1.0.3" "libqb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qb_version \- Structured library versioning info\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qbutil\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBmajor\fP"
.br
.RI "Major component\&. "
.ti -1c
.RI "uint8_t \fBminor\fP"
.br
.RI "Minor component\&. "
.ti -1c
.RI "uint8_t \fBmicro\fP"
.br
.RI "Micro component\&. "
.ti -1c
.RI "const char * \fBrest\fP"
.br
.RI "Rest (pertaining the mid-release-point) "
.in -1c
.SH "Detailed Description"
.PP 
Structured library versioning info\&. 
.SH "Field Documentation"
.PP 
.SS "uint8_t qb_version::major"

.PP
Major component\&. 
.SS "uint8_t qb_version::micro"

.PP
Micro component\&. 
.SS "uint8_t qb_version::minor"

.PP
Minor component\&. 
.SS "const char* qb_version::rest"

.PP
Rest (pertaining the mid-release-point) 

.SH "Author"
.PP 
Generated automatically by Doxygen for libqb from the source code\&.
